# Generated by Django 4.1 on 2022-09-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amigos',
            old_name='edad',
            new_name='dni',
        ),
    ]
