# Generated by Django 4.1 on 2022-09-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinal', '0002_rename_edad_amigos_dni'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amigos',
            new_name='Amigo',
        ),
        migrations.RenameModel(
            old_name='Juguetes',
            new_name='Juguete',
        ),
        migrations.RenameModel(
            old_name='Lugares',
            new_name='Lugar',
        ),
    ]
